// ============================================================
// WORDLIST - 形容詞1000個 + 名詞1000個
// カテゴリー：音楽・感情・闇・宇宙・時間・ゴシック・
//             サイバーパンク・日本語ローマ字・アニメ・オタク
// ============================================================

const ADJECTIVES = [
  // ── 音楽系 (100) ──
  "distorted","silent","resonant","dissonant","amplified",
  "overdriven","muted","feedback","tremolo","sustain",
  "reverbed","saturated","compressed","filtered","modulated",
  "pitched","detuned","harmonized","layered","syncopated",
  "offbeat","polyrhythmic","atonal","chromatic","staccato",
  "legato","fortissimo","pianissimo","accelerando","diminished",
  "augmented","inverted","transposed","improvised","remixed",
  "looped","glitched","sampled","distilled","overloaded",
  "noisy","fuzzy","wailing","droning","pulsing",
  "throbbing","buzzing","crackling","hissing","screeching",
  "thundering","roaring","whispering","echoing","vibrating",
  "oscillating","wavering","fluctuating","stuttering","clipping",
  "saturating","overdriving","phasing","flanging","chorusing",
  "arpeggiated","quantized","pitched","sequenced","looping",
  "sidechain","pumping","slamming","smashing","crushing",
  "grinding","shredding","tearing","ripping","slashing",
  "stabbing","piercing","cutting","slicing","splitting",
  "crashing","colliding","exploding","imploding","detonating",
  "igniting","blazing","scorching","burning","smoldering",
  "flickering","glowing","radiating","emanating","projecting",
  "reflecting","refracting","diffracting","dispersing","scattering",
  "absorbing","transmitting","conducting","resonating","sympathizing",

  // ── 感情・闇系 (100) ──
  "hollow","cursed","broken","bleeding","shattered",
  "twisted","haunted","forsaken","consumed","obsessed",
  "fractured","corrupted","tormented","suffocating","unraveling",
  "decaying","withering","collapsing","drowning","screaming",
  "starving","freezing","melting","crumbling","fading",
  "vanishing","dissolving","imploding","raging","grieving",
  "mourning","yearning","aching","longing","drifting",
  "sinking","falling","craving","suffering","enduring",
  "resisting","surrendering","collapsing","shattering","fracturing",
  "splintering","disintegrating","eroding","corroding","rusting",
  "rotting","festering","putrefying","decomposing","withering",
  "wilting","drooping","sagging","slumping","crumpling",
  "writhing","convulsing","trembling","shivering","quaking",
  "lurching","stumbling","reeling","staggering","faltering",
  "hesitating","doubting","fearing","dreading","loathing",
  "despising","hating","resenting","envying","coveting",
  "obsessing","fixating","spiraling","descending","plummeting",
  "crashing","burning","smoldering","seething","boiling",
  "fuming","raging","frenzied","manic","deranged",
  "unhinged","unmoored","untethered","unbound","unchained",

  // ── 時間・宇宙系 (100) ──
  "ancient","cosmic","eternal","infinite","timeless",
  "primordial","celestial","galactic","stellar","nebular",
  "quantum","relativistic","dimensional","parallel","temporal",
  "chronological","anachronistic","prehistoric","futuristic","posthumous",
  "interstellar","intergalactic","supernova","singular","gravitational",
  "orbital","eclipsed","solstice","equinox","meridian",
  "twilight","liminal","threshold","transient","ephemeral",
  "fleeting","momentary","perpetual","cyclical","recursive",
  "primeval","archaic","antediluvian","immemorial","ageless",
  "deathless","undying","immortal","everlasting","sempiternal",
  "abyssal","boundless","fathomless","immeasurable","incalculable",
  "unknowable","unfathomable","incomprehensible","inconceivable","indescribable",
  "transcendent","metaphysical","hyperdimensional","extradimensional","supradimensional",
  "subatomic","molecular","cellular","organismal","planetary",
  "solar","lunar","astral","ethereal","spectral",
  "phantom","wraith","shade","specter","apparitional",
  "ghostly","haunted","cursed","bewitched","enchanted",
  "mystical","arcane","occult","esoteric","hermetic",
  "alchemical","transmuted","transformed","transfigured","metamorphosed",
  "evolved","mutated","adapted","awakened","ascended",

  // ── ゴシック・詩的系 (100) ──
  "eldritch","macabre","sepulchral","lugubrious","tenebrous",
  "crepuscular","nocturnal","somber","funereal","mournful",
  "melancholic","despondent","desolate","forlorn","bereft",
  "wretched","harrowed","afflicted","tormented","plagued",
  "forsaken","abandoned","exiled","ostracized","shunned",
  "condemned","damned","accursed","hexed","jinxed",
  "blighted","withered","barren","desolate","wasteland",
  "ruinous","decrepit","dilapidated","crumbling","decayed",
  "weathered","eroded","corroded","tarnished","oxidized",
  "blackened","charred","scorched","ashen","pallid",
  "ghastly","cadaverous","spectral","wraithlike","incorporeal",
  "ephemeral","evanescent","fleeting","transitory","impermanent",
  "mutable","inconstant","volatile","unstable","precarious",
  "perilous","treacherous","hazardous","dangerous","lethal",
  "fatal","mortal","terminal","final","ultimate",
  "absolute","irrevocable","irreversible","immutable","unalterable",
  "inevitable","inescapable","inexorable","relentless","merciless",
  "pitiless","ruthless","remorseless","implacable","unyielding",
  "unbending","unbreakable","indomitable","invincible","unconquerable",
  "impenetrable","impervious","invulnerable","unassailable","inviolable",

  // ── サイバーパンク・SF系 (100) ──
  "synthetic","cybernetic","bionic","augmented","enhanced",
  "modified","upgraded","optimized","calibrated","synchronized",
  "networked","connected","integrated","embedded","hardwired",
  "softcoded","encrypted","compressed","compiled","executed",
  "rendered","processed","computed","calculated","simulated",
  "virtual","digital","binary","hexadecimal","algorithmic",
  "procedural","generative","recursive","iterative","fractal",
  "chaotic","entropic","stochastic","probabilistic","quantum",
  "encrypted","decrypted","encoded","decoded","obfuscated",
  "compiled","decompiled","hacked","cracked","exploited",
  "overclocked","throttled","bottlenecked","optimized","streamlined",
  "parallelized","distributed","decentralized","fragmented","defragmented",
  "corrupted","infected","quarantined","isolated","firewalled",
  "backdoored","rootkitted","trojaned","wormed","botted",
  "proxied","tunneled","routed","rerouted","redirected",
  "intercepted","monitored","surveilled","tracked","traced",
  "logged","recorded","archived","cached","indexed",
  "queried","filtered","sorted","ranked","weighted",
  "normalized","standardized","formatted","structured","parsed",
  "tokenized","vectorized","embedded","projected","classified",

  // ── 日本語ローマ字系 (100) ──
  "kuroi","akai","shiroi","aoi","midori",
  "shizuka","hagane","tsuyoi","yowai","hayai",
  "osoi","fukai","asai","takai","hikui",
  "nagai","mijikai","omoi","karui","katai",
  "yawarakai","tsumetai","atatakai","kurai","akarui",
  "kibishii","yasashii","hazukashii","sabishii","kanashii",
  "ureshii","kowai","fushigi","ayashii","kitanai",
  "utsukushii","minikui","nemui","tsurai","hageshii",
  "osoroshii","itoshii","setsunai","hakanai","natsukashii",
  "mezurashii","subarashii","tanoshii","omoshiroi","tsumaranai",
  "muzukashii","yasashii","furui","atarashii","wakai",
  "ooi","sukunai","hiroi","semai","marui",
  "shikakui","togarita","kasuka","kiyoi","nigori",
  "kawaki","nureru","nurui","karappoi","mitasareta",
  "akiru","nayamu","komaru","odoroku","yorokobu",
  "kanashimu","ikaru","osoreru","hazukashigaru","aisuru",
  "nikumu","urayamu","hokkori","pika","seku",
  "dokidoki","waku","zawa","gira","hura",
  "fura","bura","kira","moe","tsun",
  "dere","yan","kuu","dan","chi",

  // ── アニメ・オタク系 (100) ──
  "chuunibyou","kawaii","tsundere","yandere","kuudere",
  "dandere","deredere","moekko","bishoujo","bishounen",
  "kakkoii","sugoi","majime","yareyare","mendokusai",
  "nakisou","ikemen","kawaisou","setsunai","hakanai",
  "kimochi","genki","baka","erai","hentai",
  "crazed","possessed","awakened","ascended","transcendent",
  "shonen","shoujo","seinen","josei","isekai",
  "tensei","cheat","overpowered","maxlevel","legendary",
  "forbidden","sealed","released","unleashed","limitless",
  "cursed","blessed","chosen","fated","destined",
  "reincarnated","reborn","revived","resurrected","undying",
  "immortal","ageless","timeless","endless","boundless",
  "powerless","awakening","evolving","transforming","ascending",
  "descending","falling","rising","burning","blazing",
  "raging","seething","overflowing","surging","rushing",
  "crashing","smashing","piercing","cutting","slashing",
  "striking","hitting","punching","kicking","throwing",
  "summoning","conjuring","casting","channeling","manifesting",
  "materializing","crystallizing","solidifying","forming","shaping",
  "creating","destroying","erasing","negating","nullifying",

  // ── ミステリアス・魔法系 (100) ──
  "arcane","mystical","occult","esoteric","hermetic",
  "alchemical","transmuted","enchanted","bewitched","hexed",
  "charmed","cursed","blessed","anointed","consecrated",
  "sanctified","hallowed","sacred","divine","profane",
  "forbidden","taboo","heretical","blasphemous","sacrilegious",
  "unholy","ungodly","demonic","infernal","diabolical",
  "satanic","luciferian","abyssal","stygian","tartarean",
  "elysian","paradisiacal","celestial","angelic","seraphic",
  "cherubic","archangelic","divine","godlike","omnipotent",
  "omniscient","omnipresent","transcendent","immanent","ineffable",
  "numinous","luminous","radiant","resplendent","glorious",
  "magnificent","majestic","sublime","awe-inspiring","terrifying",
  "dreadful","fearsome","formidable","imposing","overwhelming",
  "crushing","devastating","annihilating","obliterating","eradicating",
  "eliminating","exterminating","extinguishing","snuffing","quenching",
  "dousing","dampening","suppressing","repressing","oppressing",
  "subjugating","dominating","controlling","commanding","ruling",
  "governing","directing","guiding","leading","following",
  "obeying","serving","worshipping","venerating","revering",
  "honoring","respecting","admiring","loving","hating",

  // ── 自然・環境系 (100) ──
  "stormy","tempestuous","turbulent","tumultuous","chaotic",
  "raging","furious","ferocious","savage","wild",
  "untamed","feral","primal","instinctual","animalistic",
  "bestial","brutal","vicious","predatory","hunting",
  "stalking","lurking","prowling","circling","closing",
  "enveloping","surrounding","engulfing","swallowing","consuming",
  "devouring","feeding","growing","spreading","expanding",
  "multiplying","proliferating","overrunning","dominating","overwhelming",
  "submerging","flooding","drowning","suffocating","choking",
  "strangling","constricting","compressing","crushing","grinding",
  "pulverizing","atomizing","vaporizing","sublimating","evaporating",
  "condensing","crystallizing","solidifying","freezing","glacial",
  "arctic","polar","frigid","icy","frozen",
  "permafrost","tundra","boreal","temperate","tropical",
  "equatorial","desert","arid","parched","scorched",
  "volcanic","magmatic","molten","incandescent","pyroclastic",
  "seismic","tectonic","geological","lithospheric","mantle",
  "oceanic","pelagic","abyssal","benthic","hadal",
  "atmospheric","stratospheric","mesospheric","thermospheric","exospheric",
  "interplanetary","interstellar","intergalactic","cosmic","universal",

  // ── 感覚・知覚系 (100) ──
  "blinding","deafening","numbing","paralyzing","stunning",
  "dazzling","mesmerizing","hypnotizing","entrancing","bewitching",
  "captivating","compelling","irresistible","overwhelming","overpowering",
  "intoxicating","euphoric","ecstatic","rapturous","transcendent",
  "sublime","ineffable","indescribable","unspeakable","unutterable",
  "profound","deep","meaningful","significant","weighty",
  "substantial","considerable","remarkable","notable","noteworthy",
  "extraordinary","exceptional","unusual","rare","unique",
  "singular","individual","specific","particular","precise",
  "exact","accurate","correct","perfect","flawless",
  "immaculate","pristine","pure","clean","clear",
  "transparent","translucent","opaque","obscure","hidden",
  "concealed","veiled","masked","shrouded","cloaked",
  "disguised","camouflaged","mimicked","imitated","copied",
  "replicated","duplicated","cloned","reproduced","multiplied",
  "amplified","magnified","intensified","strengthened","fortified",
  "hardened","toughened","tempered","annealed","quenched",
  "refined","purified","distilled","concentrated","condensed",
  "crystallized","precipitated","filtered","separated","isolated"
];

const NOUNS = [
  // ── 音楽系 (100) ──
  "riff","echo","chord","tempo","rhythm",
  "melody","harmony","frequency","amplitude","wavelength",
  "feedback","distortion","reverb","delay","chorus",
  "flanger","phaser","tremolo","vibrato","sustain",
  "overdrive","fuzz","wah","compression","saturation",
  "modulation","oscillation","resonance","timbre","texture",
  "groove","pulse","beat","measure","bar",
  "bridge","verse","hook","outro","intro",
  "solo","riff","lick","phrase","motif",
  "theme","variation","development","recapitulation","coda",
  "cadence","resolution","tension","release","climax",
  "anticlimax","denouement","epilogue","prologue","prelude",
  "interlude","postlude","fanfare","overture","suite",
  "sonata","symphony","concerto","quartet","quintet",
  "ensemble","orchestra","band","crew","collective",
  "movement","passage","section","phrase","period",
  "stanza","verse","refrain","chorus","bridge",
  "breakdown","buildup","drop","crescendo","decrescendo",
  "sforzando","fortepiano","pianissimo","fortissimo","mezzoforte",

  // ── 存在・幽霊系 (100) ──
  "phantom","specter","ghost","wraith","shade",
  "apparition","poltergeist","banshee","revenant","lich",
  "shadow","silhouette","remnant","vestige","trace",
  "imprint","memory","scar","wound","void",
  "abyss","chasm","rift","fracture","hollow",
  "absence","nothing","emptiness","silence","darkness",
  "obscurity","mystery","enigma","paradox","anomaly",
  "glitch","error","artifact","residue","fragment",
  "shard","splinter","sliver","chip","piece",
  "remnant","relic","fossil","artifact","antique",
  "heirloom","legacy","inheritance","heritage","tradition",
  "memory","recollection","flashback","echo","resonance",
  "impression","imprint","trace","mark","stain",
  "scar","wound","bruise","contusion","laceration",
  "fracture","break","rupture","tear","rip",
  "hole","gap","void","vacuum","emptiness",
  "nothingness","nonexistence","oblivion","annihilation","obliteration",
  "erasure","deletion","removal","elimination","eradication",
  "extinction","extermination","genocide","apocalypse","armageddon",
  "ragnarok","gotterdammerung","eschaton","omega","terminus",

  // ── 日本語ローマ字系 (100) ──
  "tamashii","yami","hikari","kaze","honoo",
  "mizu","tsuchi","sora","umi","yama",
  "hoshi","tsuki","taiyou","kumo","kage",
  "hibiki","kodama","mugen","kiseki","unmei",
  "inochi","kokoro","chikara","katana","yoroi",
  "oni","tenshi","akuma","ryuu","kitsune",
  "tanuki","kappa","yuki","sakura","kunoichi",
  "shinobi","samurai","ronin","shougun","daimyo",
  "katachi","sugata","iro","oto","においのない",
  "kimochi","omoi","yume","genjitsu","kako",
  "mirai","ima","toki","basho","sekai",
  "uchuu","jikan","kuukan","jigen","gensou",
  "genkai","kyoukai","sakaime","hazama","sukima",
  "tobira","tobi","hashira","ne","ha",
  "mi","hana","me","mimi","kuchi",
  "te","ashi","karada","kokoro","tamashii",
  "rei","ki","ma","en","kizuna",
  "chigiri","chikai","tigiri","noroi","jumon",
  "mahou","jutsu","ninjutsu","taijutsu","genjutsu",
  "fuuin","kekkai","barrier","kenchiku","toride",

  // ── 宇宙・SF系 (100) ──
  "void","signal","frequency","dimension","matrix",
  "protocol","algorithm","cipher","binary","quantum",
  "singularity","anomaly","paradox","continuum","vortex",
  "nebula","pulsar","quasar","blackhole","wormhole",
  "hyperspace","subspace","darkspace","nullspace","cyberspace",
  "mainframe","terminal","vector","node","grid",
  "system","network","interface","datastream","bandwidth",
  "wavelength","spectrum","radiation","plasma","antimatter",
  "darkmatter","darkenergy","cosmological","horizon","event",
  "entropy","negentropy","information","complexity","emergence",
  "consciousness","awareness","perception","cognition","intelligence",
  "sentience","sapience","wisdom","knowledge","understanding",
  "memory","storage","processing","computation","simulation",
  "reality","virtuality","actuality","potentiality","possibility",
  "probability","certainty","uncertainty","determinism","randomness",
  "chaos","order","pattern","structure","organization",
  "hierarchy","network","web","mesh","lattice",
  "crystal","matrix","array","field","force",
  "energy","matter","spacetime","fabric","texture",
  "geometry","topology","manifold","dimension","brane",

  // ── アニメ・オタク系 (100) ──
  "shinigami","nakama","senpai","jutsu","chakra",
  "zanpakuto","bankai","shikai","hokage","kage",
  "sensei","dojo","bushido","ninjutsu","taijutsu",
  "genjutsu","kekkei","genkai","rasengan","chidori",
  "kamehameha","shunpo","kidou","hakuda","zanjutsu",
  "quincy","arrancar","titan","shifter","omniverse",
  "ultrainstinct","supermode","overdrive","awakening","evolution",
  "transformation","ascension","transcendence","godmode","limitbreak",
  "ultimatetechnique","finalform","trueform","hiddenform","unsealed",
  "zanpakuto","shikai","bankai","resurreccion","volstandig",
  "sage","sagemode","bijuu","jinchuuriki","tailed",
  "sharingan","rinnegan","byakugan","mangekyo","tenseigan",
  "dojutsu","kekkei","genkai","bloodline","limit",
  "cursedtechnique","innate","domain","expansion","barrier",
  "reversal","maximum","output","simple","domain",
  "hollow","menos","adjuchas","vasto","lorde",
  "shinigami","quincy","fullbring","vizard","arrancar",
  "espada","sternritter","soul","reaper","death",
  "afterlife","soul","society","hueco","mundo",
  "dangai","royal","palace","zero","squad",

  // ── ゴシック・詩的系 (100) ──
  "elegy","requiem","dirge","lament","threnody",
  "epitaph","eulogy","eulogy","memorial","monument",
  "cenotaph","crypt","catacomb","ossuary","charnel",
  "necropolis","graveyard","cemetery","burial","ground",
  "tombstone","gravestone","headstone","marker","obelisk",
  "mausoleum","sepulcher","vault","crypt","tomb",
  "coffin","casket","shroud","winding","sheet",
  "funeral","pyre","cremation","ashes","dust",
  "remains","relics","bones","skull","skeleton",
  "phantom","specter","apparition","manifestation","materialization",
  "vision","hallucination","illusion","mirage","phantasm",
  "delusion","obsession","fixation","compulsion","addiction",
  "possession","control","domination","subjugation","enslavement",
  "bondage","captivity","imprisonment","confinement","isolation",
  "solitude","loneliness","desolation","abandonment","exile",
  "banishment","expulsion","ostracism","excommunication","damnation",
  "condemnation","judgment","sentence","verdict","punishment",
  "retribution","vengeance","revenge","justice","injustice",
  "mercy","grace","forgiveness","redemption","salvation",
  "damnation","perdition","hellfire","purgatory","limbo",

  // ── 自然・元素系 (100) ──
  "storm","tempest","hurricane","typhoon","cyclone",
  "tornado","whirlwind","maelstrom","vortex","eddy",
  "current","tide","wave","surge","swell",
  "tsunami","flood","deluge","inundation","overflow",
  "eruption","explosion","detonation","blast","shockwave",
  "earthquake","tremor","seismic","tectonic","fault",
  "avalanche","landslide","mudslide","rockfall","collapse",
  "glacier","iceberg","permafrost","tundra","boreal",
  "desert","wasteland","badlands","desolation","void",
  "canyon","gorge","ravine","chasm","abyss",
  "volcano","crater","caldera","magma","lava",
  "obsidian","basalt","granite","quartz","crystal",
  "diamond","sapphire","ruby","emerald","amethyst",
  "opal","pearl","onyx","jet","ebony",
  "ivory","bone","shell","carapace","exoskeleton",
  "spine","thorn","barb","fang","claw",
  "talon","beak","horn","antler","tusk",
  "venom","poison","toxin","acid","caustic",
  "corrosive","reactive","volatile","unstable","explosive",
  "flammable","combustible","incendiary","pyrophoric","hypergolic",

  // ── 感情・内面系 (100) ──
  "desire","craving","longing","yearning","hunger",
  "thirst","need","want","wish","hope",
  "dream","aspiration","ambition","goal","purpose",
  "meaning","significance","importance","value","worth",
  "dignity","pride","honor","shame","guilt",
  "regret","remorse","sorrow","grief","mourning",
  "despair","hopelessness","futility","meaninglessness","nihilism",
  "emptiness","numbness","apathy","indifference","detachment",
  "alienation","estrangement","isolation","loneliness","solitude",
  "connection","belonging","acceptance","rejection","exclusion",
  "love","hate","anger","fear","joy",
  "sadness","disgust","surprise","anticipation","trust",
  "distrust","suspicion","paranoia","anxiety","dread",
  "terror","panic","frenzy","hysteria","madness",
  "obsession","compulsion","addiction","dependency","attachment",
  "liberation","freedom","independence","autonomy","sovereignty",
  "power","strength","weakness","vulnerability","fragility",
  "resilience","endurance","perseverance","determination","willpower",
  "courage","bravery","cowardice","timidity","boldness",
  "recklessness","caution","prudence","wisdom","folly",

  // ── 神話・伝説系 (100) ──
  "myth","legend","prophecy","oracle","omen",
  "portent","augury","divination","prophecy","revelation",
  "vision","dream","nightmare","premonition","foreboding",
  "destiny","fate","doom","wyrd","moira",
  "karma","dharma","samsara","nirvana","moksha",
  "enlightenment","awakening","realization","understanding","gnosis",
  "logos","pneuma","sophia","agape","eros",
  "thanatos","ananke","tyche","nemesis","ate",
  "hubris","nemesis","catharsis","anagnorisis","peripeteia",
  "hamartia","pathos","ethos","logos","mythos",
  "archetype","prototype","paradigm","template","blueprint",
  "pattern","model","form","shape","structure",
  "essence","substance","matter","spirit","soul",
  "anima","animus","shadow","persona","self",
  "ego","id","superego","unconscious","subconscious",
  "collective","unconscious","archetype","complex","shadow",
  "trickster","hero","mentor","threshold","guardian",
  "shapeshifter","ally","herald","outcast","innocent",
  "ruler","caregiver","creator","destroyer","seeker",
  "lover","jester","sage","magician","orphan"
];

// ============================================================
// 使用例
// ============================================================
// QR1の文字コード合計 % 1000 → 形容詞インデックス
// QR2の文字コード合計 % 1000 → 名詞インデックス
//
// function getCharacterName(qr1, qr2) {
//   const sum1 = [...qr1].reduce((a, c) => a + c.charCodeAt(0), 0);
//   const sum2 = [...qr2].reduce((a, c) => a + c.charCodeAt(0), 0);
//   const adj = ADJECTIVES[sum1 % ADJECTIVES.length];
//   const noun = NOUNS[sum2 % NOUNS.length];
//   return `${adj} ${noun}`;
// }
//
// 例：
// "happentobe" + "machikara"
// → "glitched shinigami"
// → "quantum tamashii"
// → "yandere void"
// ============================================================

console.log(`Loaded: ${ADJECTIVES.length} adjectives, ${NOUNS.length} nouns`);
console.log(`Combinations: ${ADJECTIVES.length * NOUNS.length} (${(ADJECTIVES.length * NOUNS.length).toLocaleString()})`);
